[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.backends._legacy:_Backend"

[project]
name = "cardinality-constrained-optimisation"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "arch",
    "copulae",
    "financedatabase",
    "matplotlib",
    "muarch",
    "numpy",
    "pandas",
    "pmdarima",
    "pulp",
    "pygad",
    "scikit-posthocs",
    "scipy",
    "seaborn",
    "tqdm",
    "yfinance",
]

[tool.setuptools.packages.find]
include = ["src*"]
